name       : argyllcms
version    : 1.9.2
release    : 1
source     :
    - https://www.argyllcms.com/Argyll_V1.9.2_src.zip : 4d61ae0b91686dea721d34df2e44eaf36c88da87086fd50ccc4e999a58e9ce90
license    : GPL-3.0
component  : xorg.display
summary    : ICC compatible color management system
description: |
    ArgyllCMS is an ICC compatible color management system, available as Open Source. It supports accurate ICC profile creation for scanners, cameras and film recorders, and calibration and profiling of displays and RGB & CMYK printers. Device Link can be created with a wide variety of advanced options, including specialized Video calibration standards  and 3dLuts. Spectral sample data is supported, allowing a selection of illuminants observer types, and paper fluorescent whitener additive compensation. Profiles can also incorporate source specific gamut mappings for perceptual and saturation intents. Gamut mapping and profile linking uses the CIECAM02 appearance model, a unique gamut mapping algorithm, and a wide selection of rendering intents. It also includes code for the fastest portable 8 bit raster color conversion engine available anywhere, as well as support for fast, fully accurate 16 bit conversion. Device color gamuts can also be viewed and compared with a modern Web browser using X3DOM . Comprehensive documentation is provided for each major tool, and a general guide to using the tools for typical color management tasks is also available. A mailing list provides support for more advanced usage.
homepage   : http://www.argyllcms.com/
builddeps  :
    - pkgconfig(x11-xcb)
    - pkgconfig(xxf86vm)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xdmcp)
    - pkgconfig(libtiff-4)
    - ftjam
setup      : |
    sed -i 's|jam |/usr/local/bin/jam |g' Makefile
build      : |
    %make
install    : |
    %make_install

    mkdir -p $installdir/usr/bin
    mv $installdir/bin $installdir/usr
    mkdir -p $installdir/usr/share/color/argyll
    mv $installdir/ref $installdir/usr/share/color/argyll

