name       : argyllcms
version    : 2.2.0
release    : 11
source     :
    - https://www.argyllcms.com/Argyll_V2.2.0_src.zip : c612a2e49fd51e089616cd27b6d4717d0f20fc8edbd906462f0d0dbbabbc711c
license    :
    - AGPL-3.0-only
    - GPL-2.0-or-later
component  : xorg.display
summary    : ICC compatible color management system
description: |
    ArgyllCMS is an ICC compatible color management system, available as Open Source. It supports accurate ICC profile creation for scanners, cameras and film recorders, and calibration and profiling of displays and RGB & CMYK printers.
homepage   : https://www.argyllcms.com/
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xdmcp)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xxf86vm)
    - ftjam
setup      : |
    # Use LDFLAGS
    echo "LINKFLAGS += ${LDFLAGS} ;" >> Jamtop
build      : |
    CCOPTFLAG="$CFLAGS"
    jam -q -fJambase -j %YJOBS% -sPREFIX=/usr -sDESTDIR=$installdir -sREFSUBDIR=share/argyllcms/ref all
install    : |
    jam -q -fJambase -j %YJOBS% -sPREFIX=/usr -sDESTDIR=$installdir -sREFSUBDIR=share/argyllcms/ref install

    # wtf ???
    rm $installdir/usr/bin/License.txt

    install -D -m00644 doc/*.* -t $installdir/usr/share/argyllcms/doc/
    install -D -m00644 doc/ccmxs/*.ccmx -t installdir/usr/share/argyllcms/doc/ccmxs/

    # Note: colord provides 69-cd-sensors.rules, so it should not be necessary to install usb/55-Argyll.rules
