name       : argyllcms
version    : 2.1.0
release    : 5
source     :
    - https://www.argyllcms.com/Argyll_V2.1.0_src.zip : 57a24794248937ad67facf56af8384dfbc556d5791345ab40b2d321c2707bbcf
license    :
    - AGPL-3.0-only
    - GPL-2.0-or-later
component  : xorg.display
summary    : ICC compatible color management system
description: |
    ArgyllCMS is an ICC compatible color management system, available as Open Source. It supports accurate ICC profile creation for scanners, cameras and film recorders, and calibration and profiling of displays and RGB & CMYK printers. Device Link can be created with a wide variety of advanced options, including specialized Video calibration standards  and 3dLuts. Spectral sample data is supported, allowing a selection of illuminants observer types, and paper fluorescent whitener additive compensation. Profiles can also incorporate source specific gamut mappings for perceptual and saturation intents. Gamut mapping and profile linking uses the CIECAM02 appearance model, a unique gamut mapping algorithm, and a wide selection of rendering intents. It also includes code for the fastest portable 8 bit raster color conversion engine available anywhere, as well as support for fast, fully accurate 16 bit conversion. Device color gamuts can also be viewed and compared with a modern Web browser using X3DOM . Comprehensive documentation is provided for each major tool, and a general guide to using the tools for typical color management tasks is also available. A mailing list provides support for more advanced usage.
homepage   : https://www.argyllcms.com/
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xdmcp)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xxf86vm)
    - ftjam
setup      : |
    # Use LDFLAGS
    echo "LINKFLAGS += ${LDFLAGS} ;" >> Jamtop
build      : |
    CCOPTFLAG="$CFLAGS"
    jam -q -fJambase -j %YJOBS% -sPREFIX=/usr -sDESTDIR=$installdir -sREFSUBDIR=share/argyllcms/ref all
install    : |
    jam -q -fJambase -j %YJOBS% -sPREFIX=/usr -sDESTDIR=$installdir -sREFSUBDIR=share/argyllcms/ref install

    # wtf ???
    rm $installdir/usr/bin/License.txt

    install -D -m00644 doc/*.* -t $installdir/usr/share/argyllcms/doc/
    install -D -m00644 doc/ccmxs/*.ccmx -t installdir/usr/share/argyllcms/doc/ccmxs/

    # Note: colord provides 69-cd-sensors.rules, so it should not be necessary to install usb/55-Argyll.rules
